### ISSUE TITLE
compiling under windows

### ISSUE THREAD

**Issue by q8ing** [radareorg/r2retdec#32] opened 2021-02-03 20:16 UTC
I was trying to compile the plugin in Windows operating system, but I encountered this error:

![1](https://user-images.githubusercontent.com/52950756/106803712-87c56700-6675-11eb-93e1-f84c8058019a.png)

My radare2 is installed and working properly, I have no idea why It can't find it.

C:\Users\root\Desktop\retdec-r2plugin\build>radare2 -H
R2_VERSION=5.1.0
R2_PREFIX=.
R2_MAGICPATH=C:\Users\root\AppData\Local\Programs\radare2\dist\share\magic
R2_INCDIR=C:\Users\root\AppData\Local\Programs\radare2\dist\include\libr
R2_LIBDIR=C:\Users\root\AppData\Local\Programs\radare2\dist\lib
R2_LIBEXT=dll
R2_RCONFIGHOME=C:\Users\root\.config\radare2
R2_RDATAHOME=C:\Users\root\.local\share\radare2
R2_RCACHEHOME=C:\Users\root\.cache\radare2
R2_LIBR_PLUGINS=C:\Users\root\AppData\Local\Programs\radare2\dist\lib\plugins
R2_USER_PLUGINS=C:\Users\root\.local\share\radare2\plugins
R2_USER_ZIGNS=C:\Users\root\.local\share\radare2\zigns

Any help is appreciated.

**Comment by trufae** [comment] 2022-07-21 09:34
Can you try again? seems like retdec fixed their bugs and the plugin is working again

**Comment by trufae** [comment] 2022-07-21 09:37
dupe of #28

**Closed by trufae** 2022-07-21 09:37 UTC
